#  飞书
APP_ID: 
APP_SECRET: 
APP_ENCRYPT_KEY: 
APP_VERIFICATION_TOKEN: 
# 请确保和飞书应用管理平台中的设置一致
BOT_NAME: 
# openAI
OPENAI_KEY: 
# 服务器配置
HTTP_PORT: 9000
HTTPS_PORT: 9001
USE_HTTPS: false
CERT_FILE: cert.pem
KEY_FILE: key.pem
# openai 地址, 一般不需要修改, 除非你有自己的反向代理
API_URL: 
# 代理设置, 例如 "http://127.0.0.1:7890", ""代表不使用代理
HTTP_PROXY: ""
